name: amplify
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  image_picker: ^0.8.7+4
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.3
  email_validator: ^2.1.17
  cached_network_image: ^3.2.3
  firebase_storage: ^11.1.1
  google_sign_in: ^6.1.0
  flutter_carousel_widget: ^2.0.2
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/